# Generated by Django 5.1.2 on 2024-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayitinerary',
            name='accommodation',
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='destination',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
