# Generated by Django 5.1.2 on 2024-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madot', '0003_destination_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayitinerary',
            options={'ordering': ['day_number']},
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
