# Generated by Django 5.1.2 on 2024-11-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madot', '0004_alter_dayitinerary_options_dayitinerary_photo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='les_destinations',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
